[package]
name = "strategy-lp-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.strategy-lp]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.53.2"
default-features = false
